### ISSUE TITLE
[BUG] Moving requests out of folder

### ISSUE THREAD

**Issue by vertil** [getinsomnia/importers#11]
Hey dude!

First of all: awesome tool! I really like it!

I discovered a bug while importing requests from Postman2:

Let's assume my folder structure looks like this:
* Tool -> news -> #bunch of requests
* Tool -> schedule -> #bunch of requests

Behaviour:
If i drag an request (i'll name it "request-1") from "news" and want to put it in the "Tool"-folder, there's always the "forbidden icon", so i'm not able to move it into an folder where _no other_ request is present.

If i firstly create an random request in my "Tool"-folder and then hover my dragged request-1 over the "Tool"-folder, the line-indicator finally shows up. 

To clear things up, i made a gif:

![capture](https://user-images.githubusercontent.com/2685063/27021071-46b0afa8-4f46-11e7-9f32-d90ce2c8a54b.Gif)

Thx!

**Comment by vertil** [comment]
Sorry, missed the correct project... :-)

**Comment by gschier** [comment]
For reference, this was moved to https://github.com/getinsomnia/insomnia/issues/301
