### ISSUE TITLE
Question: How do you import from Postman?

### ISSUE THREAD

**Issue by jtabet** [getinsomnia/importers#4]
Hi,

I have a valid Postman v2 config, but Insomnia doesn't seem to recognize it and I can't select the import format in the file selection screen. When I import it as "Insomnia Import", all I get is "No importers found for file". Did I forget something to make it work properly?

I'm using Insomnia v4.0.13 on a Debian based Linux distro

**Comment by gschier** [comment]
Hi @jtabet. Sorry for the delay. I, for some reason, didn't have notifications turned on for this repo. 

If you still need this, can you give it another shot in the latest build and let me know if it still happens? If so, I'll take a look.

Also, just to make sure, is this how you exported it?

![image](https://cloud.githubusercontent.com/assets/587576/25734092/51942260-3114-11e7-8d13-22ac8ce279f1.png)

**Comment by gschier** [comment]
Closing this one for now. Let me know if you have any further questions.

**Comment by cooperkong** [comment]
Hi , I follow exactly the way to export from Postmanv2, but still getring "No importers found for file" :(

**Comment by gschier** [comment]
Hi @cooperkong.

Does your exported Postman file contain an `"info"` object with a `"schema": "https://schema.getpostman.com/json/collection/v2.0.0/collection.json"` key?

```js
{
  ...
  "info": {
    "name": "My API",
    "_postman_id": "f2b5b308-c96b-a1db-8164-2726e3032bde",
    "description": "",
    "schema": "https://schema.getpostman.com/json/collection/v2.0.0/collection.json"
  },
  ...
```

**Comment by cooperkong** [comment]
Hi @gschier 
yes it does
```
"info": {
		"name": "Mobile APIs",
		"_postman_id": "d6e2a1de-c6cc-0f79-9da9-c58298a35bd4",
		"description": "",
		"schema": "https://schema.getpostman.com/json/collection/v2.0.0/collection.json"
	},

**Comment by gschier** [comment]
Hmm, `info.schema` is the only thing that is checked ([see code](https://github.com/getinsomnia/importers/blob/b996183953d876614ffd4dd21d74468d223306ff/src/importers/postman.js#L17)), so yours should work.

What version of Insomnia are you running?

**Comment by cooperkong** [comment]
@gschier 
insomnia 5.6.3
Postman 5.1.2

**Comment by gschier** [comment]
@cooperkong would you be able to send a sanitized version of your export for me to test with?

**Comment by cooperkong** [comment]
@gschier here you go
https://gist.github.com/cooperkong/c291bd886cde793423b46b0466aebb3a

**Comment by gschier** [comment]
Sorry @cooperkong, I meant the Postman export. The one you are trying to import into Insomnia.

**Comment by cooperkong** [comment]
@gschier just updated 👍

**Comment by gschier** [comment]
Hmm, that seemed to work for me when importing to Insomnia 5.6.3

![image](https://user-images.githubusercontent.com/587576/28810617-8a785c84-763f-11e7-868c-14eeb13f2540.png)

**Comment by cooperkong** [comment]
@gschier does the one generated from insomnia-import also work for you?

**Comment by gschier** [comment]
Oh, I see the problem...

When using `insomnia-import postman.txt > export.txt`, the output is wrapped in some extra JSON data. If you take what's in the "data" attribute, it should work.

https://gist.github.com/gschier/6347a17aef00a2abb8fba5b02f82c26c

I'll fix that right away.

**Comment by gschier** [comment]
@cooperkong should be fixed in `insomnia-importers@1.4.0`

**Comment by cooperkong** [comment]
@gschier Yeah, correct, if I only take the 'data' bit it works!

**Comment by gschier** [comment]
Thanks for being patient and helping me debug that @cooperkong!
